# Generated by Codex on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_phone_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(
                choices=[
                    ("Home", "Home"),
                    ("Work", "Work"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
