# Generated by Django 6.0.6 on 2026-06-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_address_street_alter_address_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_default_delivery",
            field=models.BooleanField(default=False),
        ),
    ]
