# Generated by Django 6.0.6 on 2026-06-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_address_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyalty_coins',
            field=models.IntegerField(default=0),
        ),
    ]
