# Generated by Django 6.0.6 on 2026-07-01 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_config", "0007_siteconfig_kitchen_location"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="Notification",
                ),
            ],
        )
    ]
