# Generated by Django 6.0.6 on 2026-07-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_config", "0008_delete_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="kitchen_phone",
            field=models.CharField(
                default="+918875775282",
                help_text="Contact number for the kitchen",
                max_length=20,
            ),
        ),
    ]
