"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from dotenv import load_dotenv
import dj_database_url
from pathlib import Path
from datetime import timedelta


load_dotenv()  # Load environment variables from .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-&)it&i=k95m4jz0n^_drp_8)6so2(&c0ly^ssky+5es72x8k3v"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

# If running on Azure App Service, automatically add WEBSITE_HOSTNAME and handle internal health check IPs
if os.getenv("WEBSITE_INSTANCE_ID"):
    azure_hostname = os.getenv("WEBSITE_HOSTNAME")
    if azure_hostname and azure_hostname not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(azure_hostname)

    class AzureAllowedHosts(list):
        def __iter__(self):
            import inspect
            frame = inspect.currentframe()
            try:
                while frame:
                    if frame.f_code.co_name in ("validate_host", "<genexpr>"):
                        f = frame
                        while f:
                            if f.f_code.co_name == "validate_host":
                                host = f.f_locals.get("host", "")
                                if host:
                                    host_name = host.split(":")[0]
                                    if host_name.startswith("169.254."):
                                        return iter(["*"])
                                break
                            f = f.f_back
                        break
                    frame = frame.f_back
            except Exception:
                pass
            return super().__iter__()

    ALLOWED_HOSTS = AzureAllowedHosts(ALLOWED_HOSTS)

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    ""
).split(",") if os.getenv("CSRF_TRUSTED_ORIGINS") else []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'accounts',
    'products',
    'orders',
    "authentication",
    'app_config',
    'payments',
    'notifications',
    'delivery',
    'analytics',
    'offers',
    'loyalty',
    'support',
    'reviews',
    'rest_framework',
    'corsheaders',
    'channels',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

redis_url = os.getenv("REDIS_URL") or os.getenv("REDIS_OM_URL")
if redis_url:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [redis_url],
                "capacity": 1500,  # limit max messages in a channel before dropping
                "expiry": 10,      # message expiry in seconds
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_default_db_url = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
_database_url = os.getenv("DATABASE_URL")

try:
    _parsed_database = dj_database_url.parse(_database_url or _default_db_url)
except dj_database_url.ParseError:
    _parsed_database = dj_database_url.parse(_default_db_url)

# Supabase / PgBouncer transaction pooling (port 6543) rotates the backend
# connection per statement, so Django's server-side (named) cursors break with
# "InvalidCursorName: cursor ... does not exist". Disable them for Postgres.
if _parsed_database.get("ENGINE") == "django.db.backends.postgresql":
    _parsed_database["DISABLE_SERVER_SIDE_CURSORS"] = True

DATABASES = {
    "default": _parsed_database
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
if os.getenv("WEBSITE_INSTANCE_ID"):  # Running on Azure App Service
    MEDIA_ROOT = Path("/home/site/media")
else:
    MEDIA_ROOT = BASE_DIR / "media"


CORS_ALLOW_ALL_ORIGINS = os.getenv(
    "CORS_ALLOW_ALL_ORIGINS",
    "False"
) == "True"

CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    ""
).split(",") if os.getenv(
    "CORS_ALLOWED_ORIGINS",
    ""
) else []


AUTH_USER_MODEL = 'accounts.User'



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}


# Cashfree Payments (PG) configuration.
# CASHFREE_ENV controls which Cashfree base URL is used; flip it to
# "production" once live API keys are in place — no code change needed.
CASHFREE_APP_ID = os.getenv("CASHFREE_APP_ID", "")
CASHFREE_SECRET_KEY = os.getenv("CASHFREE_SECRET_KEY", "")
CASHFREE_ENV = os.getenv("CASHFREE_ENV", "sandbox")
CASHFREE_API_VERSION = os.getenv("CASHFREE_API_VERSION", "2023-08-01")

CASHFREE_BASE_URL = (
    "https://api.cashfree.com/pg"
    if CASHFREE_ENV == "production"
    else "https://sandbox.cashfree.com/pg"
)

CASHFREE_WEBHOOK_SECRET = os.getenv(
    "CASHFREE_WEBHOOK_SECRET",
    ""
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO" if not DEBUG else "DEBUG",
    },
    "loggers": {
        "orders.views": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

