# Generated by Django 6.0.5 on 2026-06-06 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_payment_id_order_razorpay_order_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_preparation_time",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_confirmation", "Pending Confirmation"),
                    ("confirmed", "Confirmed"),
                    ("preparing", "Preparing"),
                    ("ready_for_pickup", "Ready For Pickup"),
                    ("out_for_delivery", "Out For Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                ],
                default="pending_confirmation",
                max_length=20,
            ),
        ),
    ]
