# Generated by Django 6.0.6 on 2026-06-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_payment_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cashfree_order_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
