# Generated by Django 6.0.6 on 2026-06-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_feature_expansion"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_location_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
