# Generated by Django 6.0.6 on 2026-06-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_ordermessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coins_earned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="coins_redeemed",
            field=models.IntegerField(default=0),
        ),
    ]
