# Generated by Django 6.0.6 on 2026-06-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='not_received_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='not_received_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
