# Generated by Django 6.0.6 on 2026-07-01 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_prepconfig"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="Coupon",
                ),
                migrations.RemoveField(
                    model_name="ordermessage",
                    name="order",
                ),
                migrations.RemoveField(
                    model_name="ordermessage",
                    name="sender",
                ),
                migrations.RemoveField(
                    model_name="orderreview",
                    name="customer",
                ),
                migrations.RemoveField(
                    model_name="orderreview",
                    name="order",
                ),
                migrations.DeleteModel(
                    name="PrepConfig",
                ),
                migrations.AlterUniqueTogether(
                    name="productreview",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="productreview",
                    name="customer",
                ),
                migrations.RemoveField(
                    model_name="productreview",
                    name="order",
                ),
                migrations.RemoveField(
                    model_name="productreview",
                    name="product",
                ),
                migrations.DeleteModel(
                    name="OrderMessage",
                ),
                migrations.DeleteModel(
                    name="OrderReview",
                ),
                migrations.DeleteModel(
                    name="ProductReview",
                ),
            ],
        )
    ]
