# Generated by Django 6.0.6 on 2026-07-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_order_orders_orde_status_c6dd84_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="out_for_delivery_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="preparing_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
