# Generated by Django 6.0.6 on 2026-07-01 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="PrepConfig",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "queue_multiplier",
                            models.FloatField(
                                default=2.0,
                                help_text="Minutes added per active order in the queue",
                            ),
                        ),
                        (
                            "rush_hour_bonus",
                            models.PositiveIntegerField(
                                default=5,
                                help_text="Extra minutes added during peak hours",
                            ),
                        ),
                        (
                            "override_boost",
                            models.IntegerField(
                                default=0,
                                help_text="Manual override minutes added to all predictions",
                            ),
                        ),
                        (
                            "peak_start_time",
                            models.TimeField(default=datetime.time(18, 0)),
                        ),
                        (
                            "peak_end_time",
                            models.TimeField(default=datetime.time(22, 0)),
                        ),
                        (
                            "peak_weekdays",
                            models.CharField(
                                default="4,5,6",
                                help_text="Comma-separated weekdays for peak hours (0=Mon, 6=Sun)",
                                max_length=50,
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Preparation Configuration",
                        "db_table": "orders_prepconfig",
                    },
                ),
            ],
        )
    ]
