# Generated by Django 6.0.6 on 2026-07-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Coupon',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(max_length=50, unique=True)),
                        ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], max_length=15)),
                        ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                        ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('valid_from', models.DateTimeField(blank=True, null=True)),
                        ('valid_until', models.DateTimeField(blank=True, null=True)),
                        ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                        ('usage_count', models.PositiveIntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'orders_coupon',
                    },
                ),
            ]
        )
    ]

