name: hdk_delivery
description: "HDK Foods Delivery App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  hdk_core:
    path: ../packages/hdk_core
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_secure_storage: ^10.3.1
  google_fonts: ^6.2.1
  provider: ^6.1.5+1
  intl: ^0.19.0
  google_maps_flutter: ^2.17.1
  geolocator: ^14.0.2
  url_launcher: ^6.2.5
  flutter_polyline_points: ^2.0.1
  permission_handler: ^11.3.1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.3.0
  flutter_local_notifications: ^18.0.0
  web_socket_channel: ^3.0.1
  lottie: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
