// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMqkCr6bP38Xu92-uDrHOacmfkl9kAF7E',
    appId: '1:215110053067:web:8d35cd11abb256fca2bf4e',
    messagingSenderId: '215110053067',
    projectId: 'hdk-foods',
    authDomain: 'hdk-foods.firebaseapp.com',
    storageBucket: 'hdk-foods.firebasestorage.app',
    measurementId: 'G-69F23N7P7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTCq8bGL_rQmrTml-_DKF4cLek3nGTJK4',
    appId: '1:215110053067:android:bce4c94dbf879ebba2bf4e',
    messagingSenderId: '215110053067',
    projectId: 'hdk-foods',
    storageBucket: 'hdk-foods.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEaf--IPdR4jvK-O-7fzVeyuMsrgc1Sc0',
    appId: '1:215110053067:ios:a8b74035ccfa02f1a2bf4e',
    messagingSenderId: '215110053067',
    projectId: 'hdk-foods',
    storageBucket: 'hdk-foods.firebasestorage.app',
    iosBundleId: 'com.hdkfoods.frontend',
  );
}
